### ISSUE TITLE
Cannot buy runes if inventory full (have runes)

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#84] opened 2019-10-22 23:06 UTC
You can't buy runes from a shop if you have no space in your inventory (but already have that rune in your inventory)

**Comment by Gptaqbc** [comment] 2019-10-23 20:12
There is a little fix to do in the 2006rebotted/2006Redone Server/src/redone/game/shops/ShopAssistant.java to solve this issue. 

The problem is here :
> if (player.getItemAssistant().freeSlots() > 0)

This should be changed to also check if the player have a stack of the items he tries to buy in his inventory.

I don't know if it's possible as I can't look at all the code as of right now but it doesn't seem really hard to check the inventory for an item at this step.

**Comment by Gptaqbc** [comment] 2019-10-23 22:21
|| player.getItemAssistant().playerHasItem(itemID)

This is what needs to be added but I can seem to figure out how to know if the itemId is a stackable item. I'll be back later

**Comment by Gptaqbc** [comment] 2019-10-23 22:28
It now works for stackable items! I'll just have to do some testing to be sure it's all good.

Could I be assigned to the task real quick? thx!

**Closed** 2019-10-24 18:30 UTC
