### ISSUE TITLE
Converting items to notes and notes to items by interacting with banker/booth

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#248] opened 2019-12-09 20:04 UTC
Cannot convert items to notes by using them on the banker/bank booth.
Cannot convert notes to items by using them on the banker/bank booth.

**Comment by mrextremez** [comment] 2019-12-09 21:31
Not a bug that was added at a later date on osrs

**Comment by dginovker** [comment] 2019-12-09 21:32
Yup. I think if we wanted that we would have to poll it

**Comment by Gptaqbc** [comment] 2019-12-10 20:54
Closing this one?

**Closed** 2019-12-10 21:20 UTC
